import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './app/Livewire/**/*.php',
    ],

    darkMode: 'class',

    theme: {
        extend: {
            fontFamily: {
                sans: ['"Plus Jakarta Sans"', ...defaultTheme.fontFamily.sans],
                'body-md': ['"Plus Jakarta Sans"'],
                'label-sm': ['"Plus Jakarta Sans"'],
                'tabular-nums': ['"Plus Jakarta Sans"'],
                'headline-lg': ['"Plus Jakarta Sans"'],
                'body-lg': ['"Plus Jakarta Sans"'],
                'display-kpi': ['"Plus Jakarta Sans"'],
                'headline-lg-mobile': ['"Plus Jakarta Sans"'],
                'headline-md': ['"Plus Jakarta Sans"'],
            },
            colors: {
                // Organic Enterprise Palette
                'surface': '#fcf9f2',
                'surface-dim': '#dddad3',
                'surface-bright': '#fcf9f2',
                'surface-container-lowest': '#ffffff',
                'surface-container-low': '#f6f3ec',
                'surface-container': '#f1eee7',
                'surface-container-high': '#ebe8e1',
                'surface-container-highest': '#e5e2db',
                'on-surface': '#1c1c18',
                'on-surface-variant': '#424843',
                'inverse-surface': '#31312c',
                'inverse-on-surface': '#f4f0e9',
                'outline': '#727972',
                'outline-variant': '#c2c8c1',
                'surface-tint': '#476551',
                'primary': '#274432',
                'on-primary': '#ffffff',
                'primary-container': '#3e5c48',
                'on-primary-container': '#b1d3ba',
                'inverse-primary': '#adcfb5',
                'secondary': '#56615a',
                'on-secondary': '#ffffff',
                'secondary-container': '#d9e5dc',
                'on-secondary-container': '#5c6760',
                'tertiary': '#573701',
                'on-tertiary': '#ffffff',
                'tertiary-container': '#724e17',
                'on-tertiary-container': '#f4c280',
                'error': '#ba1a1a',
                'on-error': '#ffffff',
                'error-container': '#ffdad6',
                'on-error-container': '#93000a',
                'primary-fixed': '#c9ebd1',
                'primary-fixed-dim': '#adcfb5',
                'on-primary-fixed': '#032111',
                'on-primary-fixed-variant': '#2f4d3a',
                'secondary-fixed': '#d9e5dc',
                'secondary-fixed-dim': '#bdc9c1',
                'on-secondary-fixed': '#131e18',
                'on-secondary-fixed-variant': '#3e4943',
                'tertiary-fixed': '#ffddb4',
                'tertiary-fixed-dim': '#f0be7c',
                'on-tertiary-fixed': '#291800',
                'on-tertiary-fixed-variant': '#614008',
                'background': '#fcf9f2',
                'on-background': '#1c1c18',
                'surface-variant': '#e5e2db',
                
                // Theme Custom Aliases
                'page-bg': '#EDEAE3',
                'card-surface': '#FFFFFF',
                'text-primary': '#2A2A26',
                'text-secondary': '#8B8880',
                'border-divider': '#E7E4DC',
                'negative-rose': '#C9697A',
                'negative-bg': '#F7DEE2',
                'danger-red': '#B3413F',
                'warning-amber': '#C98A3B',
                'accent-tan-light': '#F3E4C9',

                // Retain previous layouts
                'border-subtle': '#E5E7EB',
                'text-main': '#111827',
                'text-muted': '#4B5563',
                'success': '#10B981',
                'warning': '#F59E0B',
                'danger': '#EF4444',
                'class-a': '#E0E7FF',
                'class-b': '#F3F4F6',
                'class-c': '#FFFFFF',
            },
            spacing: {
                'base': '4px',
                'xs': '4px',
                'sm': '8px',
                'md': '16px',
                'lg': '24px',
                'xl': '32px',
                'gutter': '24px',
                'margin': '32px',
                'sidebar-expanded': '240px',
                'sidebar-collapsed': '64px',
                'header-height': '88px', // matched to Stitch header-height: 88px
            },
            borderRadius: {
                'sm': '0.5rem',
                'DEFAULT': '1rem',
                'md': '1.5rem',
                'lg': '2rem',
                'xl': '3rem',
                'full': '9999px',
            },
            fontSize: {
                'label-sm': ['12px', { 'lineHeight': '16px', 'letterSpacing': '0.05em', 'fontWeight': '600' }],
                'headline-lg-mobile': ['20px', { 'lineHeight': '28px', 'fontWeight': '600' }],
                'body-md': ['14px', { 'lineHeight': '20px', 'fontWeight': '400' }],
                'body-lg': ['16px', { 'lineHeight': '24px', 'fontWeight': '400' }],
                'headline-lg': ['24px', { 'lineHeight': '32px', 'fontWeight': '600' }],
                'tabular-nums': ['14px', { 'lineHeight': '20px', 'fontWeight': '500' }],
                'headline-md': ['20px', { 'lineHeight': '28px', 'fontWeight': '600' }],
                'display-kpi': ['32px', { 'lineHeight': '40px', 'letterSpacing': '-0.02em', 'fontWeight': '700' }],
            },
            boxShadow: {
                'soft-ambient': '0 4px 12px 0 rgba(0, 0, 0, 0.08)',
            },
            maxWidth: {
                'canvas': '1440px',
            },
        },
    },

    plugins: [forms],
};
